---
- name: upload a qcow to openshift
  hosts: localhost
  become: false
  gather_facts: no
  vars_files:
    - secrets_folder/ovirt-pass
#      - /home/bdumont/vars/global_vars.yml
    - vars/provision_vars.yml
    - secrets_folder/cluster_vars.yml
  vars:
    - s3_host: minio-api-minio-tenant-new.apps.ocp-cluster.dumont-lab.lan
    
  tasks:
    - name: Retrieve a list of objects in S3 bucket
      amazon.aws.s3_object_info:
        aws_access_key: "{{ s3_user }}"
        secret_key: "{{ s3_password }}"
        endpoint_url: "https://{{ s3_host }}"
        bucket_name: images
        validate_certs: false
#    - name: Pause for 2 minutes to find file
#      ansible.builtin.pause:
#        seconds: 30
    - name: Download file to tmp location
      amazon.aws.s3_object:
        aws_access_key: "{{ s3_user }}"

        secret_key: "{{ s3_password }}"
        endpoint_url: "https://{{ s3_host }}"
        bucket: images
        object: "{{ image_file_name }}"
        dest: "vars/{{ image_file_name }}"
        validate_certs: false
        mode: get

    - name: repeat cdi upload for clusters
      ansible.builtin.include_tasks: cdi-upload-tasks.yml
      loop: "{{ cluster_info }}"
