---
- name: Provision kubervirt VMs
  hosts: localhost
  become: false
#  gather_facts: yes
  vars_files:
    - secrets_folder/ovirt-pass
#      - /home/bdumont/vars/global_vars.yml
    - vars/provision_vars.yml

  tasks:

    - name: Log in (obtain access token)
#      community.okd.openshift_auth:
      redhat.openshift.openshift_auth:
        host: "{{ openshift_host }}"
        username: bdumont
        password: "{{ ovirt_password }}"
        validate_certs: no
      register: openshift_auth_results


    - name: create vms
      kubernetes.core.k8s:
        host: "{{ openshift_host }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: false
        state: present  
        wait_timeout: 360
        namespace: virtual-machines
        template:
          path: templates/rhel9-server-medium-ansible.yml.j2
      with_sequence: count={{ vm_count }}

#    - name: add load balancer service
#      kubernetes.core.k8s:
#        host: "{{ openshift_host }}"
#        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
#        validate_certs: false
#        state: present
#        wait_timeout: 360
#        namespace: virtual-machines
#        template:
#          path: templates/vm-metallb-config.yaml.j2
#      with_sequence: count={{ vm_count }}  

