plugin: kubevirt.core.kubevirt
host_format: "{name}"
connections:
  - virtctl_proxy: False
    namespaces:
      - virtual-machines
    kubeconfig: /home/runner/.ssh/kubeconfig
#    kubeconfig: /home/bdumont
    context: admin
    network_name: vm-net

