- name: get information from an openshift host
  hosts: localhost
  become: false
  gather_facts: no
  vars_files:
    - secrets_folder/ovirt-pass
#      - /home/bdumont/vars/global_vars.yml
#    - vars/provision_vars.yml
#    - secrets_folder/cluster_vars.yml
  vars:
    - openshift_host: kvm-host3.dumont-lab.lan
    - openshift_user: bdumont

  tasks:
    - name: Log in (obtain access token)
#      community.okd.openshift_auth:
      redhat.openshift.openshift_auth:
        host: "https://api.{{ openshift_host  }}:6443"     
        username: "{{ openshift_user }}"
        password: "{{ ovirt_password }}"
        validate_certs: no
      register: openshift_auth_results

    - name: get info from openshift resource
      kubernetes.core.k8s_info:
        host: "https://api.{{ openshift_host  }}:6443"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: false
#        namespace: "{{ vm_namespace }}"
# change kind to what type of resource you want
        kind: Node
#        label_selectors:
#          - app = containerized-data-importer
      register: k8_response