---
- name: Provision kubervirt VMs
  hosts: localhost
  become: false
#  gather_facts: yes
  vars_files:
    - secrets_folder/ovirt-pass
#      - /home/bdumont/vars/global_vars.yml
    - vars/provision_vars.yml

  tasks:

    - name: Log in (obtain access token)
#      community.okd.openshift_auth:
      redhat.openshift.openshift_auth:
        host: "{{ openshift_host }}"
        username: "{{ openshift_user }}"
        password: "{{ ovirt_password }}"
        validate_certs: no
      register: openshift_auth_results


    - name: create vms
      kubernetes.core.k8s:
        host: "{{ openshift_host }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: false
        state: present  
        wait_timeout: 360
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}-{{ item }}.dumont-lab.lan"
            namespace: "{{ vm_namespace }}"
            generateName: 
          spec:
            running: true
            template:
              metadata:
                name: "{{ vm_name }}-{{ item }}.dumont-lab.lan"
                labels: 
                  compliance_policy: "{{ compliance_type }}"
                  authentication_source: lab_idm-1
#                  kubevirt.io/vm: "vm-{{ vm_name }}"
              spec:
                domain:
                  cpu:
                    cores: "{{ cores }}"
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                      - bootOrder: 1
                        disk:
                          bus: virtio
                        name: rootdisk
                    interfaces:
                      - bridge: {}
                        model: virtio
                        name: ovs-br1
                        state: present
#                        macAddress: {}
                  machine:
                    type: pc-q35-rhel8.4.0
                  resources:
                    requests:
                      memory: "{{ memory }}"
                hostname: "{{ vm_name }}-{{ item }}"
                networks:
                  - multus:
                      networkName: vm-network
                    name: ovs-br1
                volumes:
                  - cloudInitNoCloud:
                      networkData: |
                        version: 2
                        ethernets:
                          eth0:
                            dhcp4: true
                      userData: |
                        #cloud-config
                        user: kubevirt
                        password: "{{ ovirt_password }}"
                        chpasswd:
                          expire: false
                        ssh_authorized_keys: 
                          - "{{ ansible_pub_key }}"
                        hostname: "{{ vm_name }}"
                        fqdn: "{{ vm_name }}-{{ item }}.dumont-lab.lan"
                        prefer_fqdn_over_hostname: true
                    name: cloudinitdisk
                  - dataVolume:
                      name: "{{ vm_name }}-{{ item }}-rootdisk"
                    name: rootdisk
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}-{{ item }}-rootdisk"
                spec:
                  pvc:
                    accessModes:      
                      - "{{ access_mode }}"
                    resources:
                      requests:
                        storage: "{{ disk_size }}"
                    storageClassName: "{{ storage_class }}"
                    volumeMode: "{{ volume_mode }}"
                  source:      
                    pvc:
                      name: "{{ image_name }}"
                      namespace: virtual-machines
      with_sequence: count={{ vm_count }}

