- name: Download file from S3 bucket
  hosts: localhost
  become: false
#  gather_facts: yes
  vars_files:
    - secrets_folder/ovirt-pass
#      - /home/bdumont/vars/global_vars.yml
    - vars/provision_vars.yml
  vars:
    - s3_host: minio-api-minio-tenant-new.apps.ocp-cluster.dumont-lab.lan

  tasks:

    - name: Retrieve a list of objects in S3 bucket
      amazon.aws.s3_object_info:
        aws_access_key: minio
        secret_key: minio123
        endpoint_url: "https://{{ s3_host }}"
        bucket_name: images
        validate_certs: false
    - name: Pause for 2 minutes to find file
      ansible.builtin.pause:
        seconds: 30
    #- name: Download file to tmp location
    #  amazon.aws.s3_object:
    #    aws_access_key: "{{ s3_user }}"

    #    secret_key: "{{ s3_password }}"
    #    endpoint_url: "http://{{ s3_host }}"
    #    bucket: images
    #    object: rhel-9.5-x86_64-kvm.qcow2
    #    dest: vars/rhel-9.5-x86_64-kvm.qcow2
    #    mode: get

    #- name: Pause for 2 minutes to find file
    #  ansible.builtin.pause:
    #    seconds: 120